/**
 * Example data. Every record here was GENERATED by the fixture pipeline in
 * smartcity-dashboards (src/fixtures.mjs, generatePipelineRecords with cityKey
 * "fixture-city"), captured at commit cdfca39, and every one carries
 * origin "fixture" and fixture true exactly as generated.
 *
 * Nothing here was invented and nothing here is a city. The fixture generator
 * refuses street addresses, money, staff names and held city identities at
 * source, so these are the only permit records that may appear in an example.
 */
import data from "./fixture-records.json" with { type: "json" };

export type FixtureRecord = {
  recordId: string;
  subject: string;
  stage: keyof typeof data.stageLabels;
  status: string;
  place: string;
  dueLabel: string;
  origin: string;
  fixture: boolean;
};

export const FIXTURE_BASIS: string = data.basis;
export const FIXTURE_GENERATED_BY: string = data.generatedBy;
export const FIXTURE_RECORDS = data.records as FixtureRecord[];
export const FIXTURE_RECORD_COUNT: number = data.recordCount;
export const STAGE_LABELS: Record<string, string> = data.stageLabels;

/**
 * The record contract declares a MEANING (crit, warn, info, ok) and this is the
 * only place an example turns a meaning into a status carrier, which is the same
 * seam the product keeps in app.js. The record contract never names a class.
 */
export const STATUS_VOCABULARY = data.statusVocabulary as Array<{
  id: string;
  label: string;
  severity: "crit" | "warn" | "info" | "ok";
  resolved: boolean;
}>;

export function statusOf(id: string) {
  return STATUS_VOCABULARY.find((s) => s.id === id);
}

/** Counts measured from the records, never declared beside them. */
export function countsByStatus(): Array<{ id: string; label: string; count: number }> {
  return STATUS_VOCABULARY.map((s) => ({
    id: s.id,
    label: s.label,
    count: FIXTURE_RECORDS.filter((r) => r.status === s.id).length,
  }));
}
